### ISSUE TITLE
Analytics preview?

### ISSUE THREAD

**Issue by joshgarwood** [driftyco/ionic-cloud-angular#19]
Hey guys!

I've read that Analytics won't be available until after the initial Ionic 2 release, but I was wondering if there are any plans for an Analytics preview.  I ask because my project is at a point where we _need_ analytics, and once we make this decision we wont' be able to easily "switch gears" down the line.  I really want to use the Analytics yall are working on so we can keep as many services with Ionic as possible, but we need it in the very near future.  

Any updates on the progress with Analytics?  Thanks!

**Comment by imhoffd** [comment]
@joshgarwood We're working on analytics for Ionic 2! Some infrastructure changes are required to work with our existing systems, so it's taking a short while. 

@Fuiste, anything more to add?

**Comment by Fuiste** [comment]
That about covers it @dwieeb.  We'll have more to announce in the coming weeks, but things are coming along well!

**Comment by raae** [comment]
On the plan page it says:

Analytics (Preview)
An early preview of our core analytics service. Custom event tracking, data funnels, live user stats, and more.

Does this mean it is available for paid plans?

**Comment by Fuiste** [comment]
Hey @raae and @joshgarwood,  just noticed this issue was still open and wanted to make sure that you'd seen out [recent announcement](http://blog.ionic.io/focusing-on-fewer-things/) regarding the analytics service.

Essentially, in the interest of providing more support for our extant services, we're no longer continuing with the analytics portion of the Ionic Cloud.  Down the road, there's always the possibility that we could revisit it, but at present we need to focus on the core of the Cloud services.

**Comment by raae** [comment]
I see, maybe take it out of the pricing info. I thought this was referencing some new Analytics ;)
