### ISSUE TITLE
Ionic deploy progress callback

### ISSUE THREAD

**Issue by sagivf** [driftyco/ionic-cloud-angular#8]
Since ionic deploy now uses ES6 promises, there is no third params callback for progress.

![image](https://cloud.githubusercontent.com/assets/1857466/16558819/0787d60c-41f1-11e6-93da-7c37a6a42ec5.png)

Is there a new way of knowing the download progress?

**Comment by imhoffd** [comment]
@sagivf There is now an `onProgress` option for `extract()`, `download()`, and `update()`.

FYI I am keeping the Ionic 1 [migration guide](https://github.com/driftyco/ionic-cloud/wiki/Migration-Guide) up to date as best I can. I know you're doing Ionic 2, so you'll have to do the translation from v1 to v2, but the method signatures are the same. The migration guide is only for v1 because the only projects with the `ionic-platform-web-client` are v1 projects.

Let me know if this needs to be reopened.

**Comment by tobiasmuecksch** [comment]
@dwieeb please add this information to the official docs:

http://docs.ionic.io/services/deploy/
